sudo: required
services: 
  - docker

before_install:
  - docker build -t hrishikesh7/docker-frontend -f Dockerfile.dev .

script:
  - docker run hrishikesh7/docker-frontend npm run test -- --coverage