sudo: required
services: 
  - docker

before_install:
  - docker build -t hrishikesh7/docker-frontend -f Dockerfile.dev .

script:
  - docker run hrishikesh7/docker-frontend npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-frontend"
  env: "Dockerfrontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-697287477812"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"